version: "3.9"

services:
  monitoring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: monitoring_app
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    restart: unless-stopped

